import type { Metadata } from "next";
import { ThemeProvider } from '../context/ThemeContext';
import { Geist, Geist_Mono } from "next/font/google";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import LiveNotificationAlert from "@/components/LiveNotificationAlert";
import EchoListener from "@/components/EchoListener"; // اضافه شد



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazirFont = Vazirmatn({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-vazir",
});




export const metadata: Metadata = {
  title: "داشبورد پیشگامان",
  description: 'CRM Automation Portal',
  manifest: '/manifest.json', // 👈 این خط را اضافه کن
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={vazirFont.variable}>
      {/* 💡 تزریق فونت به بدنه اصلی لایوت داشبورد پورت 4000 */}
      <body className={`${vazirFont.className} antialiased bg-slate-50 text-slate-800`}>
        <ThemeProvider>
          <EchoListener /> {/* شنود زنده وب‌سوکت */}
          {children}
          {/* <LiveNotificationAlert /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
